---
swagger: "2.0"
info:
  description: "Sistema de Gestion de Documentos y Procedimientos Administrativos Electrónicos"
  version: "1.0.0"
  title: "Mara API"
host: "localhost:8080"
# host: "mara-ws.unc.edu.ar:8080"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"

paths:


  # ------------------ TIPOS DE OBJETOS DOCUMENTALES ------------------
  /tods:
    get:
      tags:
      - "Tipo Documental"
      summary: "Tipos de objetos documentales"
      description: "Listado de los tipos de objetos documentales"
      operationId: "todGet"
      parameters:
        - in: "query"
          name: "page"
          description: "Nro de página solicitada"
          required: true
          type: "number"
          format: "int32"
        - in: "query"
          name: "pageSize"
          description: "Tamaño de página deseado"
          required: true
          type: "number"
          format: "int32"
      responses:
        200:
          description: "Listado de objetos documentales"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TOD"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    x-swagger-router-controller: "tod"

  /tods/{id}:
    get:
      tags:
      - "Tipo Documental"
      summary: "Tipo de objeto documental por id"
      description: "Obtiene un tipo de objeto documental segun el id"
      operationId: "todIdGet"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificador único del tipo de objeto documental."
        required: true
        type: "string"
      responses:
        200:
          description: Tipo de objeto documental según el id provisto"
          schema:
            $ref: "#/definitions/TOD"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

    delete:
      tags:
      - "Tipo Documental"
      summary: "Eliminación de tipo de objeto documental por id"
      description: "Eliminación de un tipo de objeto documental segun el id"
      operationId: "todIdDelete"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificador del tipo de objeto documental."
        required: true
        type: "string"
      responses:
        204:
          description: "Tipo de objeto documental borrado."
          schema:
            $ref: "#/definitions/ReturnId"
        400:
          description: "Id incorrecto"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"

    x-swagger-router-controller: "tod"


   # ------------------ DOCUMENTOS ------------------
  /documents:
    get:
      tags:
      - "Documento"
      summary: "Documentos"
      description: "Listado de documentos"
      operationId: "documentGet"
      parameters:
        - in: "query"
          name: "page"
          description: "Nro de página solicitada"
          required: true
          type: "number"
          format: "int32"
        - in: "query"
          name: "pageSize"
          description: "Tamaño de página deseado"
          required: true
          type: "number"
          format: "int32"
      responses:
        200:
          description: "Listado de documentos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Document"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    x-swagger-router-controller: "document"

  /documents/{id}:
    get:
      tags:
      - "Documento"
      summary: "Documento por id"
      description: "Obtiene un documento segun el id"
      operationId: "documentIdGet"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificador único del documento."
        required: true
        type: "string"
      responses:
        200:
          description: "Documento según el id provisto"
          schema:
            $ref: "#/definitions/Document"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"

    delete:
      tags:
      - "Documento"
      summary: "Eliminación de documento por id"
      description: "Eliminación de un documento segun el id"
      operationId: "documentIdDelete"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificador del documento."
        required: true
        type: "string"
      responses:
        204:
          description: "Documento borrado."
          schema:
            $ref: "#/definitions/ReturnId"
        400:
          description: "Id incorrecto"
          schema:
            $ref: "#/definitions/Error"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"

    x-swagger-router-controller: "document"


  /documents/{id}/versions:
    get:
      tags:
      - "Documento"
      summary: "Versiones"
      description: "Lista de versiones asociadas al documento"
      operationId: "documentIdVersionGet"
      parameters:
        - name: "id"
          in: "path"
          description: "Identificador del documento."
          required: true
          type: "string"
      responses:
        200:
          description: "Listado de versiones del documento"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Version"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "document"

  /documents/{id}/activities:
    get:
      tags:
      - "Documento"
      summary: "Actividades"
      description: "Lista de actividades asociadas al documento"
      operationId: "documentIdActivityGet"
      parameters:
        - name: "id"
          in: "path"
          description: "Identificador del documento."
          required: true
          type: "string"
      responses:
        200:
          description: "Listado de actividades del documento"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Activity"
        404:
          description: "Recurso no encontrado"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Error interno del servidor"
          schema:
            $ref: "#/definitions/Error"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "document"


definitions:
  TOD:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identificador Unico."
      type:
        type: "string"
        description: "Define si es un tipo documental Document o Folder"
      label:
        type: "string"
        description: "Nombre completo del tipo de objeto documental."
      identifier:
        type: "string"
        description: "Identificador alfabetico del tipo de objeto documental utilizado para conformar el CUDAP."
      icon:
        type: "string"
        description: "Icono del tipo de objeto documental. Tamaño 16 px"
      large-icon:
        type: "string"
        description: "Icono del tipo de objeto documental. Tamaño 64 px"
      description:
        type: "string"
        description: "Descripcion del tipo de objeto documental."
      file-format:
        type: array
        description: "Listado de formato permitido de archivos adjuntos."
        items:
          type: "string"
      schemas:
        type: array
        description: "Listado de metadatos del tipo de objeto documental."
        items:
          type: "string"
      container-type:
        type: array
        description: "Listado de tipos de objetos documentales que puede contener si es un Folder."
        items:
          type: "string"
      view-url:
        type: "string"
        description: "Url de la vista de un tipo de objeto documental."
      edit-url:
        type: "string"
        description: "Url de edición de datos de la instancia del tipo de objeto documental."
      new-url:
        type: "string"
        description: "Url de creación de una instancia del tipo de objeto documental"
      links:
        type: "array"
        description: "Listado de vínculos a recursos"
        items:
          $ref: "#/definitions/Hypermedia"

  Document:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identificador Unico"
      title:
        type: "string"
        description: "Nombre único del documento (CUDAP)."
      path:
        type: "string"
        description: "Lugar en el que se encuentra contenido el documento en caso de estar dentro de algun tipo Folder"
      properties:
        type: array
        description: "Listado de metadatos del documento."
        items:
          type: "string"
      tod:
        type: object
        description: "Tipo de objeto documental al que referencia"
        $ref: "#/definitions/TOD"
      version:
        type: object
        description: "Version del documento"
        $ref: "#/definitions/Version"
      activity:
        type: object
        description: "Eventos del documento"
        $ref: "#/definitions/Activity"
      links:
        type: "array"
        description: "Listado de vínculos a recursos"
        items:
          $ref: "#/definitions/Hypermedia"

  Version:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identificador Unico"
      label:
        type: "string"
        description: "Etiqueta de número de version"
      date:
        type: "string"
        description: "Fecha de creación de la version"
      user:
        type: "string"
        description: "Usuario responsable del versionado"
      subject:
        type: "string"
        description: "Motivo por el que se creo la version"

  Activity:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identificador Unico"
      event-name:
        type: "string"
        description: "Nombre de la accion que el usuario realice, por ejemplo visualizar, crear, editar."
      event-description:
        type: "string"
        description: "Descripción de la accion que el usuario realice, por ejemplo Juan creó un item."
      date:
        type: "string"
        description: "Fecha en la que el evento ocurrió."
      user:
        type: "string"
        description: "Usuario que realizó la acción."


# ************* DEFINIONES GENERALES *************#
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"

  ReturnId:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      id:
        type: "string"

  Hypermedia:
    type: "object"
    properties:
      rel:
        type: "string"
        description: "Nombre del recurso con el que se relaciona"
      href:
        type: "string"
        description: "URL de referencia al recurso"
